spring:
  # 데이터베이스 연결 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver       # 사용하는 데이터베이스 드라이버
    url: ${DATABASE_URL} # 데이터베이스 URL
    username: ${DATABASE_USERNAME}                               # 데이터베이스 유저 이름
    password: ${DATABASE_PASSWORD}                                 # 데이터베이스 유저의 비밀번호
  # 스프링 JPA 설정
  jpa:
    hibernate:
      ddl-auto: update                             # DB 테이블 생성 전략 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8.x용 Dialect
        format_sql: true                             # 쿼리 로그를 정렬해서 출력한다
        show_sql: true                               # 실행되는 SQL 쿼리를 콘솔에 출력한다. 프로덕션 환경에서는 false로 변경해야 함.
    defer-datasource-initialization: true            # SQL 스크립트 초기화를 JPA 앤티티 매니저 초기화 이후로 지연시킨다. 이는 data.sql이 있어서 필요하다.
  sql:
    init:
      mode: always                                    # SQL 초기화 스크립트를 언제 실행할지 결정한다.

# Swagger 사용 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html                      # 스웨거 접근 경로
  api-docs:
    path: /api-docs                             # openAPI 접근 경로. default 값은 /v3/kapi-docs 이다.
  show-actuator: true                           # Spring Actuator의 endpoint까지 보여줄 것인지?
  default-consumes-media-type: application/json # request media type 의 기본 값
  default-produces-media-type: application/json # response media type 의 기본 값
  paths-to-match:                               # 해당 패턴에 매칭되는 controller만 swagger-ui에 노출한다.
    - /api/v1/**

# ===================================================================
# JWT (JSON Web Token) 관련 설정
# JWTProperties.java 레코드에 바인딩됩니다.
# ===================================================================
# JWT 토큰 설정
jwt:
  secret: ${JWT_SECRET}                    # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  access-token:
    prefix: "Bearer "
    header: Authorization                  # 액세스 토큰 헤더
    validity-in-minute: 15m                # 액세스 토큰 유효기간 (시간)
  refresh-token:
    cookie: ${JWT_REFRESH_TOKEN_COOKIE}    # 리프레시 토큰 쿠키 키
    expiration-days: 60d                    # 리프레시 토큰 유효기간 (일)
    byte-length: 64
  authority-key: roles                      # 액세스 토큰에서 권한을 가져올 키
  allowed-clock-skew-seconds: 30

# Redis
redis:
  port: 6379
  host: localhost
  auth:
    prefix: user                      # 레디스 저장에 필요한 키 값 중 접두어
    suffix: rt                        # 레디스 저장에 필요한 키 값 중 접미어
    max-token: 3                      # 최대로 발급 가능한 토큰의 수
  blacklist:
    prefix: bl
    suffix: at

kakao:
  admin-key: ${KAKAO_ADMIN_KEY}
  client-id: ${KAKAO_CLIENT_ID}
  auth:
    redirect-uri: ${KAKAO_REDIRECT_URI}
    kauth: https://kauth.kakao.com
    kapi: https://kapi.kakao.com
    connect-timeout-millis: 5000
    response-timeout-seconds: 5
    time-out-seconds: 5
  geocoding:
    dapi: https://dapi.kakao.com
    geocode-api: /v2/local/search/address.json

google:
  auth:
    client-id: ${GOOGLE_CLIENT_ID}                                  # 구글 클라우드 콘솔에서 발급받은 클라이언트 ID
    client-secret: ${GOOGLE_CLIENT_SECRET}                          # 구글 클라우드 콘솔에서 발급받은 클라이언트 보안 비밀번호
    redirect-uri: http://localhost:8080/api/v1/auth/callback/google # AuthController의 callback 엔드포인트와 일치해야 함
    oauth-api: https://oauth2.googleapis.com                         # 토큰 발급 및 인증 관련 API 주소
    api: https://www.googleapis.com                                 # 유저 정보 조회 관련 API 주소



# 암호화
encryption:
  algorithm: ${ENCRYPTION_ALGORITHM}
  secret-key: ${ENCRYPTION_SECRET_KEY} # 32자 이상의 보안키
  tag-length-bit: 128
  iv-length-byte: 12
  key-algorithm: AES

# CORS
cors:
  allowed-origins:
    - ${FRONTEND_DOMAIN}          # 프론트엔드 로컬 개발 환경
    - ${DEVELOP_SERVER_DOMAIN}    # 개발 서버 도메인
    - ${PROD_SERVER_DOMAIN}   # 운영 서버 도메인